# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run dbt tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dbt
      run: pip install dbt

    - name: Run dbt tests
      run: dbt test
